version: '2.0'
services:
  pf:
    build: .
    command: sh run.sh
    # volumes:
    #   - .:/proxy-forword
    ports:
      - '3010:3010'
      - '127.0.0.1:3009:3009'
    logging:
      driver: 'json-file'
      options:
      max-size: '50m'
    restart: always
